server:
  shutdown: graceful
  port: 8210  # dev, prod; rsc, func, etc; type; num;

spring:
  application:
    name: eureka server
  lifecycle:
    timeout-per-shutdown-phase: 10s

eureka:
  dashboard:
    path: /admin
  client:
    register-with-eureka: false #유레카 서버가 여러개일 경우 서버끼리 서로 등록하면 됨
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8210/eureka/ #todo 여러 유레카서버 만들기